### ISSUE TITLE
No documentation for binary

### ISSUE THREAD

**Issue by alexellis** [spfaffly/phantomjs-linux-armv6l#3]
Hi - I'm trying to save **2 days** of compilation by using your binary.

For me to use this I need the list of dependencies / apt-get packages required for the binary - which is likely slightly different from the amount needed for compilation.

Also - have you thought of producing a statically linked binary that would be more portable?

```
root@fca4fa17e65c:~/phantomjs-2.0.0-armv7/phantomjs-2.0.1-development-linux-armv6l# ./bin/phantomjs 
./bin/phantomjs: error while loading shared libraries: libicudata.so.48: cannot open shared object file: No such file or directory
```

Thanks

**Comment by yunqu** [comment]
@alexellis , similar problem here, but related to `libicui18n.so.52`. Have you solved the issue? 

I am guessing the only option is to spend 2 days to rebuild it, right?
